#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/security?useSSL=FALSE&serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.sky.com.sky.toolkit.mapper: debug  # 打印sql语句
spring:
  security:
    user:
      name: nba
      password: 123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



